image: node:latest

stages:
  - test

variables:
  MY_SECRET: $MY_SECRET # Use the secret variable defined in GitLab's CI/CD settings

before_script:
  - npm install && npm install jest

test:
  stage: test
  script:
    - npm test
